export const UPDATE_PRICE_SORT = 'UPDATE_PRICE_SORT';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const FAILED_TO_UPDATE_PRODUCTS = 'FAILED_TO_UPDATE_PRODUCTS';
export const UPDATE_COUNT = 'UPDATE_COUNT';
export const UPDATE_QUERY_PARAMS = 'UPDATE_QUERY_PARAMS';
export const UPDATE_LIMIT = 'UPDATE_LIMIT';
export const UPDATE_OFFSET = 'UPDATE_OFFSET';
export const UPDATE_PRODUCT_DETAILS = 'UPDATE_PRODUCT_DETAILS';
export const FAILED_TO_UPDATE_PRODUCT_DETAILS = 'FAILED_TO_UPDATE_PRODUCT_DETAILS';
export const UPDATE_CATEGORY_ID = 'UPDATE_CATEGORY_ID';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const FAILED_TO_UPDATE_CATEGORIES = 'FAILED_TO_UPDATE_CATEGORIES';
export const FAILED_TO_UPDATE_RELATED_CATEGORIES = 'FAILED_TO_UPDATE_RELATED_CATEGORIES';
export const UPDATE_RELATED_CATEGORIES = 'UPDATE_RELATED_CATEGORIES';

// user
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const FAILED_TO_CREATE_USER = 'FAILED_TO_CREATE_USER';
export const CLEAR_USER_ERRORS = 'CLEAR_USER_ERRORS';
export const FAILED_TO_AUTHENTICATE = 'FAILED_TO_AUTHENTICATE';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

// cart
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const COMPLETED_TRANSACTION = 'COMPLETED_TRANSACTION';
export const FAILED_TO_COMPLETE_PURCHASE = 'FAILED_TO_COMPLETE_PURCHASE';
export const 	UPDATE_PURCHASE_HISTORY = 'UPDATE_PURCHASE_HISTORY';
export const EMPTY_CART = 'EMPTY_CART';
export const DELETED_FROM_ITEMS = 'DELETED_FROM_ITEMS';
export const UPDATE_PURCHASE_TRENDS = 'UPDATE_PURCHASE_TRENDS';